F: [[1.,0,0,0,1,0,0],
    [0,1.,0,0,0,1,0],
    [0,0,1.,0,0,0,1],
    [0,0,0,1.,0,0,0],
    [0,0,0,0,1.,0,0],
    [0,0,0,0,0,1.,0],
    [0,0,0,0,0,0,1.]]
H: [[1.,0,0,0,0,0,0],
    [0,1.,0,0,0,0,0],
    [0,0,1.,0,0,0,0],
    [0,0,0,1.,0,0,0]]
R:  [[  1,  0,  0,  0],
     [ 0,   1,  0,  0],
     [ 0,  0, 1e2,  0],
     [ 0,  0,  0, 1e2]]
P:  [[  1e2,     0,     0,     0,     0,     0,     0],
     [    0,   1e2,     0,     0,     0,     0,     0],
     [    0,     0,   1e2,     0,     0,     0,     0],
     [    0,     0,     0,   1e2,     0,     0,     0],
     [    0,     0,     0,     0,   1e4,     0,     0],
     [    0,     0,     0,     0,     0,   1e4,     0],
     [    0,     0,     0,     0,     0,     0,   1e4]]
Q:    [[   1, 0, 0, 0, 0, 0, 0],
       [0,    1, 0, 0, 0, 0, 0],
       [0, 0,    1, 0, 0, 0, 0],
       [0, 0, 0,    1, 0, 0, 0],
       [0, 0, 0, 0, 1e-2, 0, 0],
       [0, 0, 0, 0, 0, 1e-2, 0],
       [0, 0, 0, 0, 0, 0, 1e-4]]


