version: '3.9'
services:
  mct_backend:
    stdin_open: true
    tty: true

    ############# EITHER ###########
    build:
      context: .
      dockerfile: Dockerfile   # relative to context
    # image: image_mct_backend
    ################################

    container_name: "laptq_mct_backend"
    entrypoint: ["/bin/bash"]
    ports:
      - "5555:5555"
    volumes:
      - .:/home/MCT       # relative to this file

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
              # - gpu
              # - utility # nvidia-smi
              # - compute # CUDA. Required to avoid "CUDA version: N/A"
              # - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
            count: all
