@startuml
|Manager|
start
:request to view cameras;
|System|
repeat
repeat while (tracking service has started?) is (no)
->yes;
:draw staff tracking result to camera view;
:stream camera view to the display;
stop
@enduml