@startuml
|Manager|
start
:request to view cameras;
|System|
repeat
:check if tracking service has started;
repeat while () is (no)
->yes;
:draw staff tracking result to camera view;
:stream camera view to the display;
stop
@enduml