@startuml
|Staff|
start
:request to manage workshift;
|System|
:provide the time slot options;
|Staff|
:select time slot;
|System|
:check for conflicts;
if () then (no)
    :save new workshift;
    stop
else (yes)
    :announce the registration was failed;
    stop
@enduml