@startuml
start
repeat
    :capture synchronized camera streams;
    :track and associate staff between cameras;
    :calculate staff's staying time;
repeat while (the day shift ends?) is (no)
->yes;
:save staying time;
stop
@enduml