@startuml
|Guess|
start
:request to sign-in;
|System|
:provide sign-in input fields;
|Guess|
:enter sign-in info;
|System|
if (sign-in info is correct?) then (no)
    :announce sign-in was failed;
    stop
else (yes)
    if (the signed-in account is staff?) then (no)
        stop
    else (yes)
        |Camera|
        :capture check-in region;
        |System|
        if (a person detection appears in check-in region?) then (yes)
            :record check-in time and assign staff to the detection;
            if (recorded check-in time > shift start time?) then (yes)
                :notify manager about the staff's arrival;
            else (no)
                stop
            endif
        else (no)
            stop
        endif
    endif
    stop
endif
@enduml