@startuml
|Guess|
start
:request to sign-in;
|System|
:provide sign-in input fields;
|Guess|
:enter sign-in info;
|System|
: check if sign-in info is correct;
if () then (no)
    :announce sign-in was failed;
    stop
else (yes)
    : check if the signed-in account is staff;
    if () then (no)
        stop
    else (yes)
        |Camera|
        :capture check-in region;
        |System|
        : check if a person detection appears in check-in region;
        if () then (yes)
            :record check-in time and assign staff to the detection;
            :check if recorded check-in time > shift start time;
            if () then (yes)
                :notify manager about the staff's arrival;
            else (no)
                stop
            endif
        else (no)
            stop
        endif
    endif
    stop
endif
@enduml