@startuml
left to right direction

:Manager: as Manager
:Guess: as Guess
:Staff: as Staff
:Admin: as Admin

rectangle System {
    (Manage accounts) as (UC09)
    (Sign out) as (UC02)
    (Manage staffs) as (UC04)
    (View real-time cameras) as (UC03)
    (Manage workshifts) as (UC16)
    (Manage personal info) as (UC17)    
    (Sign in) as (UC01)
}





UC09 -[hidden]l- UC02
UC02 -[hidden]l- UC03
UC03 -[hidden]l- UC04
UC03 -[hidden]d- UC17
UC04 -[hidden]d- UC16
UC16 -[hidden]l- UC01


UC16 -down- Staff
UC17 -- Staff
UC02 -- Staff
Manager -down- UC04
Manager -- UC02
Manager -- UC03
Admin -down- UC09
Admin -- UC02
UC01 -down- Guess

@enduml