@startuml
left to right direction

:Staff: as Staff

rectangle System {
    (Sign out) as (UC02)        
    (View staff workshifts) as (UC08)
    (View staff personal info) as (UC07)
        
}

Staff -- UC02
Staff -down- UC07
Staff -- UC08

@enduml