@startuml

:Staff: as Staff

rectangle System {
    (View staff workshifts) as UC08
    (Register new workshift) as UC14
    (Delete a workshift) as UC15
}

Staff -- UC08

UC14 .> UC08: <<extends>>
UC15 .> UC08: <<extends>>

@enduml