@startuml

allowmixing

actor Staff

class DeleteWorkshiftBoundary <<boundary>> {
    - day: String
    - dayshift_name: String
    
    - validate_current_user(): Boolean
    + set_day(): void
    + set_dayshift(): void
    + submit(): void
}

class ManageWorkshiftController <<control>> {

    + delete_workshift(): void
}

class User <<entity>> {
    - username: String
    - workshifts: List<RegisteredWorkshift>
}

class RegisteredWorkshift <<entity>> {
    - day: String
    - dayshift: DayShift
}

class DayShift <<entity>> {
    - name: String
    - start_time: Time
    - end_time: Time
}

Staff -> DeleteWorkshiftBoundary
DeleteWorkshiftBoundary -right-> ManageWorkshiftController
ManageWorkshiftController -right-> User
User o-- RegisteredWorkshift
RegisteredWorkshift *-- DayShift

@enduml
