@startuml

allowmixing

actor Staff

class RegisterWorkshiftBoundary <<boundary>> {
    - day: String
    - dayshift_name: String

    - validate_current_user(): Boolean
    + set_day(): void
    + set_dayshift(): void
    + submit(): void
}

class ManageWorkshiftController <<control>> {

    + register_workshift(): void
}

class User <<entity>> {
    - username: String
    - workshifts: List<RegisteredWorkshift>
}

class RegisteredWorkshift <<entity>> {
    - day: String
    - dayshift: DayShift
}

class DayShift <<entity>> {
    - name: String
    - start_time: Time
    - end_time: Time
}

Staff -> RegisterWorkshiftBoundary
RegisterWorkshiftBoundary -right-> ManageWorkshiftController
ManageWorkshiftController -right-> User
ManageWorkshiftController -> RegisteredWorkshift
ManageWorkshiftController -> DayShift
User o-- RegisteredWorkshift
RegisteredWorkshift *-- DayShift

@enduml
