@startuml

allowmixing

actor Guess

class SignBoundary <<boundary>> {
    - username: String
    - password: String
    
    + set_username(): void
    + set_password(): void
    + submit(): void
}

class AuthController <<control>> {

    + signin(): void
}

class User <<entity>> {
    - username: String
    - password: String
}

class Monitor <<entity>>

Guess -> SignBoundary
SignBoundary -right-> AuthController
AuthController -right-> User
AuthController -right-> Monitor
User -[hidden]d- Monitor

@enduml