@startuml

class LoginBoundary <<boundary>> {
    - username: String
    - password: String
    
    + set_username(): void
    + set_password(): void
    + submit(): void
}

class LoginController <<control>> {

    + login(): void
}

class User <<entity>> {
    - username: String
    - password: String
}

class Monitor <<entity>>

LoginBoundary --> LoginController
LoginController --> User
LoginController --> Monitor

@enduml