@startuml

allowmixing

actor Manager

class ViewCamerasBoundary <<boundary>> {
    - session_id: Integer

    - validate_current_user(): Boolean
    + submit(): void
}

class ViewCamerasController <<control>> {

    + view_cameras(): List<Generator> 
}

class Monitor <<entity>> {
    - visualize_pipelines: Dictionary<Integer, VisualizePipeline>
}

class VisualizePipeline <<entity>> {
    - output_queues: Dictionary<Integer, Queue>
}

class Queue <<entity>> {
    - id: Integer
}

Manager -> ViewCamerasBoundary
ViewCamerasBoundary -right-> ViewCamerasController
ViewCamerasController -right-> Monitor
Monitor o--> VisualizePipeline
Monitor --> Queue
VisualizePipeline o-- Queue

@enduml