@startuml

allowmixing

actor Manager

class ViewMessagesBoundary <<boundary>> {

    - validate_current_user(): Boolean
    + submit(): void
}

class MessageController <<control>> {

    + messages(): Dictionary
}

class User <<entity>> {
    - messages_received: List<Message>
}

class Message <<entity>> {
    - body: String
    - timestamp: Datetime
}

Manager -> ViewMessagesBoundary
ViewMessagesBoundary -right-> MessageController
MessageController -right-> User
MessageController -> Message
User o-- Message

@enduml