@startuml

allowmixing

actor Manager

class ViewWeeklyScheduleBoundary <<boundary>> {

    - validate_current_user(): Boolean
    + submit(): void
}

class ViewWeeklyScheduleController <<control>> {

    + weekly_schedule(): Dictionary
}

class User <<entity>> {
    - username: String
    - workshifts: List<RegisteredWorkshift>
}

class RegisteredWorkshift <<entity>> {
    - day: String
    - dayshift: DayShift
}

class DayShift <<entity>> {
    - name: String
    - start_time: Time
    - end_time: Time
}

Manager -> ViewWeeklyScheduleBoundary
ViewWeeklyScheduleBoundary -right-> ViewWeeklyScheduleController
ViewWeeklyScheduleController -right-> User
ViewWeeklyScheduleController --> RegisteredWorkshift
ViewWeeklyScheduleController --> DayShift
User -[hidden]d- RegisteredWorkshift
RegisteredWorkshift -[hidden]d- DayShift
User o-- RegisteredWorkshift
RegisteredWorkshift *-- DayShift


@enduml