@startuml

class ViewMessagesBoundary <<boundary>> {

    - validate_current_user(): Boolean
    + submit(): void
}

class MessageController <<control>> {

    + messages(): Dictionary
}

class User <<entity>> {
    - messages_received: List<Message>
}

class Message <<entity>> {
    - body: String
    - timestamp: Datetime
}

ViewMessagesBoundary --> MessageController
MessageController --> User
User o-- Message

@enduml