@startuml

allowmixing

actor Actor
actor Manager
actor Staff

class ViewStaffPersonalInfoBoundary <<boundary>> {
    - username: String
    
    - validate_current_user(): Boolean
    + set_username(): void
    + submit(): void
}

class ManageStaffsController <<control>> {

    + user_info(): Dictionary
}

class User <<entity>> {
    - name: String
    - phone: String
    - email: String
    - username: String
    - role: String
}

Manager -up-|> Actor
Staff -up-|> Actor
Actor -> ViewStaffPersonalInfoBoundary
ViewStaffPersonalInfoBoundary -right-> ManageStaffsController
ManageStaffsController -right-> User

@enduml