@startuml

allowmixing

actor Manager

class ViewCamerasBoundary <<boundary>> {
    - session_id: Integer

    - validate_current_user(): Boolean
    + submit(): void
}

class ManageStaffsController <<control>> {

    + view_cameras(): List<Generator> 
}

class Monitor <<entity>> {
    - pl_visualizes: Dictionary<Integer, VisualizePipeline>
    - started: Boolean
}

class CameraPipeline <<entity>> {
    - output_queues: Dictionary<Integer, Queue>
}

class MCMapPipeline <<entity>> {
    - output_queues: Dictionary<Integer, Queue>
}

class VisualizePipeline <<entity>> {
    - iq_annot: Queue
    - iq_video: Queue
    - output_queues: Dictionary<Integer, Queue>
}

class Queue <<entity>> {
    - id: Integer
}

Manager -> ViewCamerasBoundary
ViewCamerasBoundary -right-> ManageStaffsController
ManageStaffsController -right-> Monitor
Monitor o--> VisualizePipeline
Monitor --> Queue
CameraPipeline o--> Queue
MCMapPipeline o--> Queue
VisualizePipeline *--> Queue

@enduml