@startuml

class ViewStaffPersonalInfoBoundary <<boundary>> {
    - username: String
    
    - validate_current_user(): Boolean
    + set_username(): void
    + submit(): void
}

class ManageStaffsController <<control>> {

    + user_info(): Dictionary
}

class User <<entity>> {
    - username: String
    - role: String
}

ViewStaffPersonalInfoBoundary --> ManageStaffsController
ManageStaffsController --> User

@enduml