"""empty message

Revision ID: 63216369d13a
Revises: d4c1bdb1b658
Create Date: 2023-06-07 15:41:32.862653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63216369d13a'
down_revision = 'd4c1bdb1b658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productivity', schema=None) as batch_op:
        batch_op.alter_column('staying',
               existing_type=sa.FLOAT(),
               type_=sa.Interval(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productivity', schema=None) as batch_op:
        batch_op.alter_column('staying',
               existing_type=sa.Interval(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
