"""empty message

Revision ID: d4c1bdb1b658
Revises: 518570e5c703
Create Date: 2023-06-07 15:18:07.591188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c1bdb1b658'
down_revision = '518570e5c703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dayshift_id', sa.Integer(), nullable=True),
    sa.Column('arrival', sa.Time(), nullable=True),
    sa.Column('staying', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dayshift_id'], ['day_shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('frame_time', sa.Time(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('detection_mode', sa.String(length=140), nullable=True),
    sa.Column('tracking_mode', sa.String(length=140), nullable=True),
    sa.Column('det', sa.String(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cam_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['date'], ['productivity.date'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('det_id_1', sa.Integer(), nullable=True),
    sa.Column('det_id_2', sa.Integer(), nullable=True),
    sa.Column('loc_infer_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['det_id_1'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['det_id_2'], ['detection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sta')
    op.drop_table('detection')
    op.drop_table('productivity')
    # ### end Alembic commands ###
