@startsalt

{^==add new staff
    {/ Home }

    .
    Create account
    .
    {
        Full name | "Tran Quoc Lap"
        Phone | "             "
        Email | "             "
        Address | "             "
        Username | "laptq        "
        Password | "****         "
        Repeat password | "****         "
        Role | ^Select role ^ manager^ sales associate^ warehouse staff ^
    }
    .
    [create]
    .
}

@endsalt
