@startsalt

{^==register workshift
    {/ Home }

    .
    Register workshift
    .
    {
        Day | ^Monday              ^
        Shift | ^ Select             ^ morning (8:30 - 12:00) ^ afternoon (13:30 - 16:00) ^
    }
    .
    [register]
    .
}

@endsalt
