@startsalt

{^==register workshift
    {/ Home }

    .
    Register workshift
    .
    {
        Day | ^Monday^
        Shift | ^Select^ morning^ afternoon^
    }
    .
    [register]
    .
}

@endsalt
