@startsalt

{^==staff info
    {/ Home }

    .
    Staff info 
    .
    {
        Name: | Tran Quoc Lap
        Email: | lap.tq194443@sis.hust.edu.vn
        Role: | intern
    }
    .
    [New workshift]
    .
    Registered workshifts
    {-
        Day | Shift | Start time | End time | .
        Monday | morning | 08:30 | 12:00 | [unregister]
        Tuesday | afternoon | 13:30 | 18:00 | [unregister]
    }
    .
}

@endsalt
