@startsalt

{^==staff list
    {/ Home }

    .
    Staff list 
    .
    [New staff]
    .
    {#
        Name | Role | Productivity
        Manh PC  | engineer | 100% <&arrow-circle-right> Details
        Lap TQ | intern | 50% <&arrow-circle-right> Details

    }
    .
    .
}

@endsalt
