


# queue
QUEUE_MAXSIZE: 0
QUEUE_GET_BLOCK: false
QUEUE_PUT_BLOCK: false
QUEUE_TIMEOUT: null
QUEUE_GET_MANY_SIZE: 'all' # 100, 'all'

# camera pipeline
CAMERA_SLEEP: 0
CAMERA_FRAME_WIDTH: null
CAMERA_FRAME_HEIGHT: null
CAMERA_FPS: null

# SCT pipeline
SCT_TXT_SLEEP: 0
DETECTION_MODE: 'box'
TRACKING_MODE: 'bytetrack'

# STA pipeline
MIN_SAMPLE_SIZE_TO_FP_FILTER: 15


# display pipeline
DISPLAY_FPS: 1