


# queue
QUEUE_MAXSIZE: 0
QUEUE_GET_BLOCK: false
QUEUE_PUT_BLOCK: false
QUEUE_TIMEOUT: null
QUEUE_GET_MANY_SIZE: 'all' # 100, 'all'

# camera pipeline
CAMERA_SLEEP: 0
CAMERA_FRAME_WIDTH: null
CAMERA_FRAME_HEIGHT: null
CAMERA_FPS: null

# SCT pipeline
SCT_TXT_SLEEP: 0
DETECTION_MODE: 'pose'
TRACKING_MODE: 'bytetrack'
LOC_INFER_MODE: 1

# STA pipeline
FP_FILTER: null   # null, 'gmm', 'iqr'
MIN_SAMPLE_SIZE_TO_FP_FILTER: 15
FP_GMM_N_COMPONENTS: 2
FP_GMM_STD_COEF: 3
FP_IQR_LOWER: 30
FP_IQR_UPPER: 70
MIN_TIME_CORRESPONDENCES: 10
TIME_DIFF_THRESH: null
DIST_WINDOW_SIZE: 1
DIST_WINDOW_BOUNDARY: 0

# Scene
ROI_TEST_OFFSET: -5

# Visualizer
VIS_SCT_BOX_THICKNESS: 2
VIS_SCT_LOC_RADIUS: 8
VIS_ROI_THICKNESS: 2


# display pipeline
DISPLAY_FPS: 1