@startuml
left to right direction

node Client <<device>> {
    artifact WebBrowser
}

node WebServer {
    artifact Flask
}

database Database

Client -down- WebServer : HTTP/S requests
WebServer -down- Database : Read/write data

@enduml