@startuml

actor Manager as A
boundary CreateAccountBoundary as B2
control ManageStaffsController as C
entity User as E

A -> B2: choose to add new staff
B2 -> B2: validate_current_user()
A -> B2: set_name(name)
A -> B2: set_phone(phone)
A -> B2: set_email(email)
A -> B2: set_username(username)
A -> B2: set_password(password)
A -> B2: set_role(role)
A -> B2: set_address(address)
A -> B2: submit()
B2 -> C: create_account(username,\n password, role)
C -> E: <<create>>(username,\n password, role)

@enduml