@startuml

actor Guess as A
boundary SigninBoundary as B
control SigninController as C
entity User
entity Monitor


A -> B: choose to signin
A -> B: set_username(username: String)
A -> B: set_password(password: String)
A -> B: submit()
B -> C: signin(username: String, \n password: String)
C -> User: check_password(password: String)
C -> Monitor: signal_signin(user_id: Integer)

@enduml