@startuml

actor Guess as A
boundary SigninBoundary as B
control AuthController as C
entity User
entity Monitor


A -> B: choose to signin
A -> B: set_username(username)
A -> B: set_password(password)
A -> B: submit()
B -> C: signin(username, \n password)
C -> User: check_password(password)
C -> Monitor: signal_signin(user_id)

@enduml