@startuml

actor Actor as A
boundary ViewStaffPersonalInfoBoundary as B1
control ManageStaffsController as C
entity User as E


A -> B1: choose to view staff info
B1 -> B1: validate_current_user()
alt Actor is Manager
    A -> B1: set_username(username)
end
A -> B1: submit()



B1 -> C: user_info(username)
C -> E: <<get>>(key) 


@enduml